version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 20
    groups:
      unit-testing:
        patterns:
          - 'vitest'
          - '@vitest/*'
          - 'jsdom'
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - 'typescript-eslint'
          - 'globals'
      build-tools:
        patterns:
          - 'vite'
          - 'typescript'
          - 'tsdown'
          - '@arethetypeswrong/*'
          - 'agadoo'
          - 'dpdm'
      publishing:
        patterns:
          - '@changesets/*'
      formatting:
        patterns:
          - 'prettier'
          - 'prettier-plugin-*'
      dev-tools:
        patterns:
          - 'husky'
          - 'lint-staged'
          - 'is-ci'
          - 'bundlesize2'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 20
    groups:
      github-actions:
        patterns:
          - '*'
